name: mysql_manager
description: MySQLManager is a dependency thought to be used as a controller for the connection to MySql.
version: 1.0.1
homepage: https://github.com/raul94a/mysql_manager

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
